MvcHilos/Models/ErrorViewModel.cs
namespace MvcHilos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcHilos/Models/ListaNumeros.cs
namespace MvcHilos.Models
{
    public class ListaNumeros
    {
        
        public List<int> Multiplos { get; set; }
        public List<int> Potencias { get; set; }

        
    }
}

MvcHilos/Controllers/CalculadoraController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MvcHilos.Models;


namespace MvcHilos.Controllers
{
    public class CalculadoraController : Controller
    {
        public ListaNumeros numeros;
        public CalculadoraController()
        {
            this.numeros = new ListaNumeros();
            this.numeros.Multiplos = new List<int>();
            this.numeros.Potencias = new List<int>();
        }
        
        public ActionResult Index()
        {
            return View();
        }

      


        public void Multiplos(int num1)
        {
      
            for (int i = 0; i < 9; i++)
            {
                this.numeros.Multiplos.Add(num1 * i);
            }
         
        }

        public void Potencias(int num1)
        {
          
            for (int i = 0; i < 9; i++)
            {
                this.numeros.Potencias.Add(1);
                for (int j = 0; j < i; j++)
                {
                    this.numeros.Potencias[i] = this.numeros.Potencias[i] * num1;
                }
            }
        }


        [HttpPost]
        public ActionResult Index(int num1)
        {
            ViewData["NUMERO"] = num1;

            Thread hilo1 = new Thread(() => Multiplos(num1));
            Thread hilo2 = new Thread(() => Potencias(num1));

            hilo1.Start();
            hilo2.Start();

            return View(this.numeros);
        }
    }
}

MvcHilos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcHilos.Models;
using System.Diagnostics;

namespace MvcHilos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcHilos/Views/Calculadora/Index.cshtml
@model ListaNumeros
<h2>Calculadora</h2>


<form method="post">
    <h2>Introduzca un número</h2>
    <input type="number" name="num1" />
   
    <button type="submit">Operar</button>
</form>

@if(Model!=null){


    <div class="container">
        <div class="row">

     <div class ="col-md-6">
                <h2>Potencias</h2>
            @for(int i = 0; i <= Model.Potencias.Count; i++)
            {
                <h2> @ViewData["NUMERO"] ^ @i = @Model.Potencias[i] </h2>
            }
     </div>

      <div class="col-md-6">
            <h2>Múltiplos</h2>
            @for (int i = 0; i < Model.Multiplos.Count; i++)
            {
                        <h2> @ViewData["NUMERO"] X @i = @Model.Multiplos[i] </h2>
            }
       </div>

    </div>
    </div>
}

MvcHilos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcHilos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcHilos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcHilos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcHilos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcHilos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>